#pragma once

#define MAX_INTERVAL_MINUTE 120
#define MAX_INTERVAL_MINUTE_GLOBAL 60
#define UNIT_INTERVAL_MINUTE 10
#define BRUTAL_INTERVAL 10

#define CEPT_WRITING_MAX 70

#define IMPORTANCE_COST 1
#define IMPORTANCE_TIME 1

